// This file is auto-generated by @hey-api/openapi-ts

import type { ResendError } from "../api.ts";
import type {
  Client,
  Options as Options2,
  TDataShape,
} from "../../util/api/client/index.ts";
import { client } from "./client.gen.ts";
import type {
  DeleteApiKeysByApiKeyIdData,
  DeleteApiKeysByApiKeyIdResponses,
  DeleteAudiencesByAudienceIdContactsByEmailData,
  DeleteAudiencesByAudienceIdContactsByEmailResponses,
  DeleteAudiencesByAudienceIdContactsByIdData,
  DeleteAudiencesByAudienceIdContactsByIdResponses,
  DeleteAudiencesByIdData,
  DeleteAudiencesByIdResponses,
  DeleteBroadcastsByIdData,
  DeleteBroadcastsByIdResponses,
  DeleteDomainsByDomainIdData,
  DeleteDomainsByDomainIdResponses,
  GetApiKeysData,
  GetApiKeysResponses,
  GetAudiencesByAudienceIdContactsByEmailData,
  GetAudiencesByAudienceIdContactsByEmailResponses,
  GetAudiencesByAudienceIdContactsByIdData,
  GetAudiencesByAudienceIdContactsByIdResponses,
  GetAudiencesByAudienceIdContactsData,
  GetAudiencesByAudienceIdContactsResponses,
  GetAudiencesByIdData,
  GetAudiencesByIdResponses,
  GetAudiencesData,
  GetAudiencesResponses,
  GetBroadcastsByIdData,
  GetBroadcastsByIdResponses,
  GetBroadcastsData,
  GetBroadcastsResponses,
  GetDomainsByDomainIdData,
  GetDomainsByDomainIdResponses,
  GetDomainsData,
  GetDomainsResponses,
  GetEmailsByEmailIdData,
  GetEmailsByEmailIdResponses,
  PatchAudiencesByAudienceIdContactsByEmailData,
  PatchAudiencesByAudienceIdContactsByEmailResponses,
  PatchAudiencesByAudienceIdContactsByIdData,
  PatchAudiencesByAudienceIdContactsByIdResponses,
  PatchDomainsByDomainIdData,
  PatchDomainsByDomainIdResponses,
  PatchEmailsByEmailIdData,
  PatchEmailsByEmailIdResponses,
  PostApiKeysData,
  PostApiKeysResponses,
  PostAudiencesByAudienceIdContactsData,
  PostAudiencesByAudienceIdContactsResponses,
  PostAudiencesData,
  PostAudiencesResponses,
  PostBroadcastsByIdSendData,
  PostBroadcastsByIdSendResponses,
  PostBroadcastsData,
  PostBroadcastsResponses,
  PostDomainsByDomainIdVerifyData,
  PostDomainsByDomainIdVerifyResponses,
  PostDomainsData,
  PostDomainsResponses,
  PostEmailsBatchData,
  PostEmailsBatchResponses,
  PostEmailsByEmailIdCancelData,
  PostEmailsByEmailIdCancelResponses,
  PostEmailsData,
  PostEmailsResponses,
} from "./types.gen.ts";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

class _HeyApiClient {
  protected _client: Client = client;

  constructor(args?: {
    client?: Client;
  }) {
    if (args?.client) {
      this._client = args.client;
    }
  }
}

export class ResendClient extends _HeyApiClient {
  /**
   * Send an email
   */
  public postEmails<ThrowOnError extends boolean = true>(
    options?: Options<PostEmailsData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).post<
      PostEmailsResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/emails",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Retrieve a single email
   */
  public getEmailsByEmailId<ThrowOnError extends boolean = true>(
    options: Options<GetEmailsByEmailIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).get<
      GetEmailsByEmailIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/emails/{email_id}",
      ...options,
    });
  }

  /**
   * Update a single email
   */
  public patchEmailsByEmailId<ThrowOnError extends boolean = true>(
    options: Options<PatchEmailsByEmailIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).patch<
      PatchEmailsByEmailIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/emails/{email_id}",
      ...options,
    });
  }

  /**
   * Cancel the schedule of the e-mail.
   */
  public postEmailsByEmailIdCancel<ThrowOnError extends boolean = true>(
    options: Options<PostEmailsByEmailIdCancelData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).post<
      PostEmailsByEmailIdCancelResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/emails/{email_id}/cancel",
      ...options,
    });
  }

  /**
   * Trigger up to 100 batch emails at once.
   */
  public postEmailsBatch<ThrowOnError extends boolean = true>(
    options?: Options<PostEmailsBatchData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).post<
      PostEmailsBatchResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/emails/batch",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Retrieve a list of domains
   */
  public getDomains<ThrowOnError extends boolean = true>(
    options?: Options<GetDomainsData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).get<
      GetDomainsResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/domains",
      ...options,
    });
  }

  /**
   * Create a new domain
   */
  public postDomains<ThrowOnError extends boolean = true>(
    options?: Options<PostDomainsData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).post<
      PostDomainsResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/domains",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Remove an existing domain
   */
  public deleteDomainsByDomainId<ThrowOnError extends boolean = true>(
    options: Options<DeleteDomainsByDomainIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).delete<
      DeleteDomainsByDomainIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/domains/{domain_id}",
      ...options,
    });
  }

  /**
   * Retrieve a single domain
   */
  public getDomainsByDomainId<ThrowOnError extends boolean = true>(
    options: Options<GetDomainsByDomainIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).get<
      GetDomainsByDomainIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/domains/{domain_id}",
      ...options,
    });
  }

  /**
   * Update an existing domain
   */
  public patchDomainsByDomainId<ThrowOnError extends boolean = true>(
    options: Options<PatchDomainsByDomainIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).patch<
      PatchDomainsByDomainIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/domains/{domain_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Verify an existing domain
   */
  public postDomainsByDomainIdVerify<ThrowOnError extends boolean = true>(
    options: Options<PostDomainsByDomainIdVerifyData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).post<
      PostDomainsByDomainIdVerifyResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/domains/{domain_id}/verify",
      ...options,
    });
  }

  /**
   * Retrieve a list of API keys
   */
  public getApiKeys<ThrowOnError extends boolean = true>(
    options?: Options<GetApiKeysData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).get<
      GetApiKeysResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/api-keys",
      ...options,
    });
  }

  /**
   * Create a new API key
   */
  public postApiKeys<ThrowOnError extends boolean = true>(
    options?: Options<PostApiKeysData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).post<
      PostApiKeysResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/api-keys",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Remove an existing API key
   */
  public deleteApiKeysByApiKeyId<ThrowOnError extends boolean = true>(
    options: Options<DeleteApiKeysByApiKeyIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).delete<
      DeleteApiKeysByApiKeyIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/api-keys/{api_key_id}",
      ...options,
    });
  }

  /**
   * Retrieve a list of audiences
   */
  public getAudiences<ThrowOnError extends boolean = true>(
    options?: Options<GetAudiencesData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).get<
      GetAudiencesResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences",
      ...options,
    });
  }

  /**
   * Create a list of contacts
   */
  public postAudiences<ThrowOnError extends boolean = true>(
    options?: Options<PostAudiencesData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).post<
      PostAudiencesResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Remove an existing audience
   */
  public deleteAudiencesById<ThrowOnError extends boolean = true>(
    options: Options<DeleteAudiencesByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).delete<
      DeleteAudiencesByIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{id}",
      ...options,
    });
  }

  /**
   * Retrieve a single audience
   */
  public getAudiencesById<ThrowOnError extends boolean = true>(
    options: Options<GetAudiencesByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).get<
      GetAudiencesByIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{id}",
      ...options,
    });
  }

  /**
   * Retrieve a list of contacts
   */
  public getAudiencesByAudienceIdContacts<ThrowOnError extends boolean = true>(
    options: Options<GetAudiencesByAudienceIdContactsData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).get<
      GetAudiencesByAudienceIdContactsResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts",
      ...options,
    });
  }

  /**
   * Create a new contact
   */
  public postAudiencesByAudienceIdContacts<ThrowOnError extends boolean = true>(
    options: Options<PostAudiencesByAudienceIdContactsData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).post<
      PostAudiencesByAudienceIdContactsResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Remove an existing contact by email
   */
  public deleteAudiencesByAudienceIdContactsByEmail<
    ThrowOnError extends boolean = true,
  >(
    options: Options<
      DeleteAudiencesByAudienceIdContactsByEmailData,
      ThrowOnError
    >,
  ) {
    return (options.client ?? this._client).delete<
      DeleteAudiencesByAudienceIdContactsByEmailResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts/{email}",
      ...options,
    });
  }

  /**
   * Retrieves a single contact by email
   */
  public getAudiencesByAudienceIdContactsByEmail<
    ThrowOnError extends boolean = true,
  >(
    options: Options<GetAudiencesByAudienceIdContactsByEmailData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).get<
      GetAudiencesByAudienceIdContactsByEmailResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts/{email}",
      ...options,
    });
  }

  /**
   * Update a single contact by email
   */
  public patchAudiencesByAudienceIdContactsByEmail<
    ThrowOnError extends boolean = true,
  >(
    options: Options<
      PatchAudiencesByAudienceIdContactsByEmailData,
      ThrowOnError
    >,
  ) {
    return (options.client ?? this._client).patch<
      PatchAudiencesByAudienceIdContactsByEmailResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts/{email}",
      ...options,
    });
  }

  /**
   * Remove an existing contact by id
   */
  public deleteAudiencesByAudienceIdContactsById<
    ThrowOnError extends boolean = true,
  >(
    options: Options<DeleteAudiencesByAudienceIdContactsByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).delete<
      DeleteAudiencesByAudienceIdContactsByIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts/{id}",
      ...options,
    });
  }

  /**
   * Retrieve a single contact by id
   */
  public getAudiencesByAudienceIdContactsById<
    ThrowOnError extends boolean = true,
  >(options: Options<GetAudiencesByAudienceIdContactsByIdData, ThrowOnError>) {
    return (options.client ?? this._client).get<
      GetAudiencesByAudienceIdContactsByIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts/{id}",
      ...options,
    });
  }

  /**
   * Update a single contact by id
   */
  public patchAudiencesByAudienceIdContactsById<
    ThrowOnError extends boolean = true,
  >(
    options: Options<PatchAudiencesByAudienceIdContactsByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).patch<
      PatchAudiencesByAudienceIdContactsByIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/audiences/{audience_id}/contacts/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Retrieve a list of broadcasts
   */
  public getBroadcasts<ThrowOnError extends boolean = true>(
    options?: Options<GetBroadcastsData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).get<
      GetBroadcastsResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/broadcasts",
      ...options,
    });
  }

  /**
   * Create a broadcast
   */
  public postBroadcasts<ThrowOnError extends boolean = true>(
    options?: Options<PostBroadcastsData, ThrowOnError>,
  ) {
    return (options?.client ?? this._client).post<
      PostBroadcastsResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/broadcasts",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options?.headers,
      },
    });
  }

  /**
   * Remove an existing broadcast that is in the draft status
   */
  public deleteBroadcastsById<ThrowOnError extends boolean = true>(
    options: Options<DeleteBroadcastsByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).delete<
      DeleteBroadcastsByIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/broadcasts/{id}",
      ...options,
    });
  }

  /**
   * Retrieve a single broadcast
   */
  public getBroadcastsById<ThrowOnError extends boolean = true>(
    options: Options<GetBroadcastsByIdData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).get<
      GetBroadcastsByIdResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/broadcasts/{id}",
      ...options,
    });
  }

  /**
   * Send or schedule a broadcast
   */
  public postBroadcastsByIdSend<ThrowOnError extends boolean = true>(
    options: Options<PostBroadcastsByIdSendData, ThrowOnError>,
  ) {
    return (options.client ?? this._client).post<
      PostBroadcastsByIdSendResponses,
      ResendError,
      ThrowOnError
    >({
      url: "/broadcasts/{id}/send",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
