// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://api.resend.com" | (string & {});
};

export type SendEmailRequest = {
  /**
   * Sender email address. To include a friendly name, use the format "Your Name <sender@domain.com>".
   */
  from: string;
  to: Array<string>;
  /**
   * Email subject.
   */
  subject: string;
  /**
   * Bcc recipient email address. For multiple addresses, send as an array of strings.
   */
  bcc?: string;
  /**
   * Cc recipient email address. For multiple addresses, send as an array of strings.
   */
  cc?: string;
  /**
   * Reply-to email address. For multiple addresses, send as an array of strings.
   */
  reply_to?: string;
  /**
   * The HTML version of the message.
   */
  html?: string;
  /**
   * The plain text version of the message.
   */
  text?: string;
  /**
   * Custom headers to add to the email.
   */
  headers?: {
    [key: string]: unknown;
  };
  /**
   * Schedule email to be sent later. The date should be in ISO 8601 format.
   */
  scheduled_at?: string;
  attachments?: Array<Attachment>;
  tags?: Array<Tag>;
};

export type Attachment = {
  /**
   * Content of an attached file.
   */
  content?: Blob | File;
  /**
   * Name of attached file.
   */
  filename?: string;
  /**
   * Path where the attachment file is hosted
   */
  path?: string;
  /**
   * Optional content type for the attachment, if not set it will be derived from the filename property
   */
  content_type?: string;
};

export type Tag = {
  /**
   * The name of the email tag. It can only contain ASCII letters (a–z, A–Z), numbers (0–9), underscores (_), or dashes (-). It can contain no more than 256 characters.
   */
  name?: string;
  /**
   * The value of the email tag.It can only contain ASCII letters (a–z, A–Z), numbers (0–9), underscores (_), or dashes (-). It can contain no more than 256 characters.
   */
  value?: string;
};

export type SendEmailResponse = {
  /**
   * The ID of the sent email.
   */
  id?: string;
};

export type UpdateEmailOptions = {
  /**
   * Schedule email to be sent later. The date should be in ISO 8601 format.
   */
  scheduled_at?: string;
};

export type Email = {
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The ID of the email.
   */
  id?: string;
  to?: Array<string>;
  /**
   * The email address of the sender.
   */
  from?: string;
  /**
   * The date and time the email was created.
   */
  created_at?: string;
  /**
   * The subject line of the email.
   */
  subject?: string;
  /**
   * The HTML body of the email.
   */
  html?: string;
  /**
   * The plain text body of the email.
   */
  text?: string;
  /**
   * The email addresses of the blind carbon copy recipients.
   */
  bcc?: Array<string>;
  /**
   * The email addresses of the carbon copy recipients.
   */
  cc?: Array<string>;
  /**
   * The email addresses to which replies should be sent.
   */
  reply_to?: Array<string>;
  /**
   * The status of the email.
   */
  last_event?: string;
};

export type CreateBatchEmailsResponse = {
  data?: Array<{
    /**
     * The ID of the sent email.
     */
    id?: string;
  }>;
};

export type CreateDomainRequest = {
  /**
   * The name of the domain you want to create.
   */
  name: string;
  /**
   * The region where emails will be sent from. Possible values are us-east-1' | 'eu-west-1' | 'sa-east-1
   */
  region?: "us-east-1" | "eu-west-1" | "sa-east-1";
};

export type CreateDomainResponse = {
  /**
   * The ID of the domain.
   */
  id?: string;
  /**
   * The name of the domain.
   */
  name?: string;
  /**
   * The date and time the domain was created.
   */
  created_at?: string;
  /**
   * The status of the domain.
   */
  status?: string;
  records?: Array<DomainRecord>;
  /**
   * The region where the domain is hosted.
   */
  region?: string;
};

export type UpdateDomainOptions = {
  /**
   * Track the open rate of each email.
   */
  open_tracking?: boolean;
  /**
   * Track clicks within the body of each HTML email.
   */
  click_tracking?: boolean;
  /**
   * enforced | opportunistic.
   */
  tls?: string;
};

export type DomainRecord = {
  /**
   * The type of record.
   */
  record?: string;
  /**
   * The name of the record.
   */
  name?: string;
  /**
   * The type of record.
   */
  type?: string;
  /**
   * The time to live for the record.
   */
  ttl?: string;
  /**
   * The status of the record.
   */
  status?: string;
  /**
   * The value of the record.
   */
  value?: string;
  /**
   * The priority of the record.
   */
  priority?: number;
};

export type Domain = {
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The ID of the domain.
   */
  id?: string;
  /**
   * The name of the domain.
   */
  name?: string;
  /**
   * The status of the domain.
   */
  status?: string;
  /**
   * The date and time the domain was created.
   */
  created_at?: string;
  /**
   * The region where the domain is hosted.
   */
  region?: string;
  records?: Array<DomainRecord>;
};

export type VerifyDomainResponse = {
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The ID of the domain.
   */
  id?: string;
};

export type ListDomainsResponse = {
  data?: Array<ListDomainsItem>;
};

export type ListDomainsItem = {
  /**
   * The ID of the domain.
   */
  id?: string;
  /**
   * The name of the domain.
   */
  name?: string;
  /**
   * The status of the domain.
   */
  status?: string;
  /**
   * The date and time the domain was created.
   */
  created_at?: string;
  /**
   * The region where the domain is hosted.
   */
  region?: string;
};

export type UpdateDomainResponseSuccess = {
  /**
   * The ID of the updated domain.
   */
  id?: string;
  /**
   * The object type representing the updated domain.
   */
  object?: string;
};

export type DeleteDomainResponse = {
  /**
   * The type of object.
   */
  object?: string;
  /**
   * The ID of the domain.
   */
  id?: string;
  /**
   * Indicates whether the domain was deleted successfully.
   */
  deleted?: boolean;
};

export type CreateApiKeyRequest = {
  /**
   * The API key name.
   */
  name: string;
  /**
   * The API key can have full access to Resend’s API or be only restricted to send emails. * full_access - Can create, delete, get, and update any resource. * sending_access - Can only send emails.
   */
  permission?: "full_access" | "sending_access";
  /**
   * Restrict an API key to send emails only from a specific domain. Only used when the permission is sending_acces.
   */
  domain_id?: string;
};

export type CreateApiKeyResponse = {
  /**
   * The ID of the API key.
   */
  id?: string;
  /**
   * The token of the API key.
   */
  token?: string;
};

export type ListApiKeysResponse = {
  data?: Array<ApiKey>;
};

export type ApiKey = {
  /**
   * The ID of the API key.
   */
  id?: string;
  /**
   * The name of the API key.
   */
  name?: string;
  /**
   * The date and time the API key was created.
   */
  created_at?: string;
};

export type CreateAudienceOptions = {
  /**
   * The name of the audience you want to create.
   */
  name: string;
};

export type CreateAudienceResponseSuccess = {
  /**
   * The ID of the audience.
   */
  id?: string;
  /**
   * The object of the audience.
   */
  object?: string;
  /**
   * The name of the audience.
   */
  name?: string;
};

export type GetAudienceResponseSuccess = {
  /**
   * The ID of the audience.
   */
  id?: string;
  /**
   * The object of the audience.
   */
  object?: string;
  /**
   * The name of the audience.
   */
  name?: string;
  /**
   * The date that the object was created.
   */
  created_at?: string;
};

export type RemoveAudienceResponseSuccess = {
  /**
   * The ID of the audience.
   */
  id?: string;
  /**
   * The object of the audience.
   */
  object?: string;
  /**
   * The deleted attribute indicates that the corresponding audience has been deleted.
   */
  deleted?: boolean;
};

export type ListAudiencesResponseSuccess = {
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * Array containing audience information.
   */
  data?: Array<{
    /**
     * Unique identifier for the audience.
     */
    id?: string;
    /**
     * Name of the audience.
     */
    name?: string;
    /**
     * Timestamp indicating when the audience was created.
     */
    created_at?: string;
  }>;
};

export type CreateContactOptions = {
  /**
   * Email address of the contact.
   */
  email: string;
  /**
   * First name of the contact.
   */
  first_name?: string;
  /**
   * Last name of the contact.
   */
  last_name?: string;
  /**
   * Indicates if the contact is unsubscribed.
   */
  unsubscribed?: boolean;
  /**
   * Unique identifier of the audience to which the contact belongs.
   */
  audience_id?: string;
};

export type CreateContactResponseSuccess = {
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * Unique identifier for the created contact.
   */
  id?: string;
};

export type GetContactResponseSuccess = {
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * Unique identifier for the contact.
   */
  id?: string;
  /**
   * Email address of the contact.
   */
  email?: string;
  /**
   * First name of the contact.
   */
  first_name?: string;
  /**
   * Last name of the contact.
   */
  last_name?: string;
  /**
   * Timestamp indicating when the contact was created.
   */
  created_at?: string;
  /**
   * Indicates if the contact is unsubscribed.
   */
  unsubscribed?: boolean;
};

export type UpdateContactOptions = {
  /**
   * Email address of the contact.
   */
  email?: string;
  /**
   * First name of the contact.
   */
  first_name?: string;
  /**
   * Last name of the contact.
   */
  last_name?: string;
  /**
   * Indicates the subscription status of the contact.
   */
  unsubscribed?: boolean;
};

export type UpdateContactResponseSuccess = {
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * Unique identifier for the updated contact.
   */
  id?: string;
};

export type RemoveContactResponseSuccess = {
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * Unique identifier for the removed contact.
   */
  id?: string;
  /**
   * Indicates whether the contact was successfully deleted.
   */
  deleted?: boolean;
};

export type ListContactsResponseSuccess = {
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * Array containing contact information.
   */
  data?: Array<{
    /**
     * Unique identifier for the contact.
     */
    id?: string;
    /**
     * Email address of the contact.
     */
    email?: string;
    /**
     * First name of the contact.
     */
    first_name?: string;
    /**
     * Last name of the contact.
     */
    last_name?: string;
    /**
     * Timestamp indicating when the contact was created.
     */
    created_at?: string;
    /**
     * Indicates if the contact is unsubscribed.
     */
    unsubscribed?: boolean;
  }>;
};

export type CreateBroadcastOptions = {
  /**
   * Name of the broadcast.
   */
  name?: string;
  /**
   * Unique identifier of the audience this broadcast will be sent to.
   */
  audience_id: string;
  /**
   * The email address of the sender.
   */
  from: string;
  /**
   * The subject line of the email.
   */
  subject: string;
  /**
   * The email addresses to which replies should be sent.
   */
  reply_to?: Array<string>;
  /**
   * The preview text of the email.
   */
  preview_text?: string;
  /**
   * The HTML version of the message.
   */
  html?: string;
  /**
   * The plain text version of the message.
   */
  text?: string;
};

export type CreateBroadcastResponseSuccess = {
  /**
   * The ID of the broadcast.
   */
  id?: string;
  /**
   * The object type of the response.
   */
  object?: string;
};

export type ListBroadcastsResponseSuccess = {
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * Array containing broadcast information.
   */
  data?: Array<{
    /**
     * Unique identifier for the broadcast.
     */
    id?: string;
    /**
     * Name of the broadcast.
     */
    name?: string;
    /**
     * Unique identifier of the audience this broadcast will be sent to.
     */
    audience_id?: string;
    /**
     * The status of the broadcast.
     */
    status?: string;
    /**
     * Timestamp indicating when the broadcast was created.
     */
    created_at?: string;
    /**
     * Timestamp indicating when the broadcast is scheduled to be sent.
     */
    scheduled_at?: string;
    /**
     * Timestamp indicating when the broadcast was sent.
     */
    sent_at?: string;
  }>;
};

export type GetBroadcastResponseSuccess = {
  /**
   * Unique identifier for the broadcast.
   */
  id?: string;
  /**
   * Name of the broadcast.
   */
  name?: string;
  /**
   * Unique identifier of the audience this broadcast will be sent to.
   */
  audience_id?: string;
  /**
   * The email address of the sender.
   */
  from?: string;
  /**
   * The subject line of the email.
   */
  subject?: string;
  /**
   * The email addresses to which replies should be sent.
   */
  reply_to?: Array<string>;
  /**
   * The preview text of the email.
   */
  preview_text?: string;
  /**
   * The status of the broadcast.
   */
  status?: string;
  /**
   * Timestamp indicating when the broadcast was created.
   */
  created_at?: string;
  /**
   * Timestamp indicating when the broadcast is scheduled to be sent.
   */
  scheduled_at?: string;
  /**
   * Timestamp indicating when the broadcast was sent.
   */
  sent_at?: string;
};

export type RemoveBroadcastResponseSuccess = {
  /**
   * The ID of the broadcast.
   */
  id?: string;
  /**
   * Type of the response object.
   */
  object?: string;
  /**
   * The deleted attribute indicates that the corresponding broadcast has been deleted.
   */
  deleted?: boolean;
};

export type SendBroadcastOptions = {
  /**
   * Schedule email to be sent later. The date should be in ISO 8601 format.
   */
  scheduled_at?: string;
};

export type SendBroadcastResponseSuccess = {
  /**
   * The ID of the broadcast.
   */
  id?: string;
};

export type PostEmailsData = {
  body?: SendEmailRequest;
  headers?: {
    /**
     * A unique identifier for the request to ensure emails are only sent once. [Learn more](https://resend.com/docs/dashboard/emails/idempotency-keys)
     */
    "Idempotency-Key"?: string;
  };
  path?: never;
  query?: never;
  url: "/emails";
};

export type PostEmailsResponses = {
  /**
   * OK
   */
  200: SendEmailResponse;
};

export type PostEmailsResponse = PostEmailsResponses[keyof PostEmailsResponses];

export type GetEmailsByEmailIdData = {
  body?: never;
  path: {
    /**
     * The ID of the email.
     */
    email_id: string;
  };
  query?: never;
  url: "/emails/{email_id}";
};

export type GetEmailsByEmailIdResponses = {
  /**
   * OK
   */
  200: Email;
};

export type GetEmailsByEmailIdResponse =
  GetEmailsByEmailIdResponses[keyof GetEmailsByEmailIdResponses];

export type PatchEmailsByEmailIdData = {
  body?: never;
  path: {
    /**
     * The ID of the email.
     */
    email_id: string;
  };
  query?: never;
  url: "/emails/{email_id}";
};

export type PatchEmailsByEmailIdResponses = {
  /**
   * OK
   */
  200: UpdateEmailOptions;
};

export type PatchEmailsByEmailIdResponse =
  PatchEmailsByEmailIdResponses[keyof PatchEmailsByEmailIdResponses];

export type PostEmailsByEmailIdCancelData = {
  body?: never;
  path: {
    /**
     * The ID of the email.
     */
    email_id: string;
  };
  query?: never;
  url: "/emails/{email_id}/cancel";
};

export type PostEmailsByEmailIdCancelResponses = {
  /**
   * OK
   */
  200: Email;
};

export type PostEmailsByEmailIdCancelResponse =
  PostEmailsByEmailIdCancelResponses[keyof PostEmailsByEmailIdCancelResponses];

export type PostEmailsBatchData = {
  body?: Array<SendEmailRequest>;
  headers?: {
    /**
     * A unique identifier for the request to ensure emails are only sent once. [Learn more](https://resend.com/docs/dashboard/emails/idempotency-keys)
     */
    "Idempotency-Key"?: string;
  };
  path?: never;
  query?: never;
  url: "/emails/batch";
};

export type PostEmailsBatchResponses = {
  /**
   * OK
   */
  200: CreateBatchEmailsResponse;
};

export type PostEmailsBatchResponse =
  PostEmailsBatchResponses[keyof PostEmailsBatchResponses];

export type GetDomainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/domains";
};

export type GetDomainsResponses = {
  /**
   * OK
   */
  200: ListDomainsResponse;
};

export type GetDomainsResponse = GetDomainsResponses[keyof GetDomainsResponses];

export type PostDomainsData = {
  body?: CreateDomainRequest;
  path?: never;
  query?: never;
  url: "/domains";
};

export type PostDomainsResponses = {
  /**
   * OK
   */
  201: CreateDomainResponse;
};

export type PostDomainsResponse =
  PostDomainsResponses[keyof PostDomainsResponses];

export type DeleteDomainsByDomainIdData = {
  body?: never;
  path: {
    /**
     * The ID of the domain.
     */
    domain_id: string;
  };
  query?: never;
  url: "/domains/{domain_id}";
};

export type DeleteDomainsByDomainIdResponses = {
  /**
   * OK
   */
  200: DeleteDomainResponse;
};

export type DeleteDomainsByDomainIdResponse =
  DeleteDomainsByDomainIdResponses[keyof DeleteDomainsByDomainIdResponses];

export type GetDomainsByDomainIdData = {
  body?: never;
  path: {
    /**
     * The ID of the domain.
     */
    domain_id: string;
  };
  query?: never;
  url: "/domains/{domain_id}";
};

export type GetDomainsByDomainIdResponses = {
  /**
   * OK
   */
  200: Domain;
};

export type GetDomainsByDomainIdResponse =
  GetDomainsByDomainIdResponses[keyof GetDomainsByDomainIdResponses];

export type PatchDomainsByDomainIdData = {
  body?: UpdateDomainOptions;
  path: {
    /**
     * The ID of the domain.
     */
    domain_id: string;
  };
  query?: never;
  url: "/domains/{domain_id}";
};

export type PatchDomainsByDomainIdResponses = {
  /**
   * OK
   */
  200: UpdateDomainResponseSuccess;
};

export type PatchDomainsByDomainIdResponse =
  PatchDomainsByDomainIdResponses[keyof PatchDomainsByDomainIdResponses];

export type PostDomainsByDomainIdVerifyData = {
  body?: never;
  path: {
    /**
     * The ID of the domain.
     */
    domain_id: string;
  };
  query?: never;
  url: "/domains/{domain_id}/verify";
};

export type PostDomainsByDomainIdVerifyResponses = {
  /**
   * OK
   */
  200: VerifyDomainResponse;
};

export type PostDomainsByDomainIdVerifyResponse =
  PostDomainsByDomainIdVerifyResponses[keyof PostDomainsByDomainIdVerifyResponses];

export type GetApiKeysData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api-keys";
};

export type GetApiKeysResponses = {
  /**
   * OK
   */
  200: ListApiKeysResponse;
};

export type GetApiKeysResponse = GetApiKeysResponses[keyof GetApiKeysResponses];

export type PostApiKeysData = {
  body?: CreateApiKeyRequest;
  path?: never;
  query?: never;
  url: "/api-keys";
};

export type PostApiKeysResponses = {
  /**
   * OK
   */
  201: CreateApiKeyResponse;
};

export type PostApiKeysResponse =
  PostApiKeysResponses[keyof PostApiKeysResponses];

export type DeleteApiKeysByApiKeyIdData = {
  body?: never;
  path: {
    /**
     * The API key ID.
     */
    api_key_id: string;
  };
  query?: never;
  url: "/api-keys/{api_key_id}";
};

export type DeleteApiKeysByApiKeyIdResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetAudiencesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/audiences";
};

export type GetAudiencesResponses = {
  /**
   * OK
   */
  200: ListAudiencesResponseSuccess;
};

export type GetAudiencesResponse =
  GetAudiencesResponses[keyof GetAudiencesResponses];

export type PostAudiencesData = {
  body?: CreateAudienceOptions;
  path?: never;
  query?: never;
  url: "/audiences";
};

export type PostAudiencesResponses = {
  /**
   * OK
   */
  201: CreateAudienceResponseSuccess;
};

export type PostAudiencesResponse =
  PostAudiencesResponses[keyof PostAudiencesResponses];

export type DeleteAudiencesByIdData = {
  body?: never;
  path: {
    /**
     * The Audience ID.
     */
    id: string;
  };
  query?: never;
  url: "/audiences/{id}";
};

export type DeleteAudiencesByIdResponses = {
  /**
   * OK
   */
  200: RemoveAudienceResponseSuccess;
};

export type DeleteAudiencesByIdResponse =
  DeleteAudiencesByIdResponses[keyof DeleteAudiencesByIdResponses];

export type GetAudiencesByIdData = {
  body?: never;
  path: {
    /**
     * The Audience ID.
     */
    id: string;
  };
  query?: never;
  url: "/audiences/{id}";
};

export type GetAudiencesByIdResponses = {
  /**
   * OK
   */
  200: GetAudienceResponseSuccess;
};

export type GetAudiencesByIdResponse =
  GetAudiencesByIdResponses[keyof GetAudiencesByIdResponses];

export type GetAudiencesByAudienceIdContactsData = {
  body?: never;
  path: {
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts";
};

export type GetAudiencesByAudienceIdContactsResponses = {
  /**
   * OK
   */
  200: ListContactsResponseSuccess;
};

export type GetAudiencesByAudienceIdContactsResponse =
  GetAudiencesByAudienceIdContactsResponses[keyof GetAudiencesByAudienceIdContactsResponses];

export type PostAudiencesByAudienceIdContactsData = {
  body?: CreateContactOptions;
  path: {
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts";
};

export type PostAudiencesByAudienceIdContactsResponses = {
  /**
   * OK
   */
  201: CreateContactResponseSuccess;
};

export type PostAudiencesByAudienceIdContactsResponse =
  PostAudiencesByAudienceIdContactsResponses[keyof PostAudiencesByAudienceIdContactsResponses];

export type DeleteAudiencesByAudienceIdContactsByEmailData = {
  body?: never;
  path: {
    /**
     * The Contact email.
     */
    email: string;
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts/{email}";
};

export type DeleteAudiencesByAudienceIdContactsByEmailResponses = {
  /**
   * OK
   */
  200: RemoveContactResponseSuccess;
};

export type DeleteAudiencesByAudienceIdContactsByEmailResponse =
  DeleteAudiencesByAudienceIdContactsByEmailResponses[keyof DeleteAudiencesByAudienceIdContactsByEmailResponses];

export type GetAudiencesByAudienceIdContactsByEmailData = {
  body?: never;
  path: {
    /**
     * The Contact email.
     */
    email: string;
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts/{email}";
};

export type GetAudiencesByAudienceIdContactsByEmailResponses = {
  /**
   * OK
   */
  200: GetContactResponseSuccess;
};

export type GetAudiencesByAudienceIdContactsByEmailResponse =
  GetAudiencesByAudienceIdContactsByEmailResponses[keyof GetAudiencesByAudienceIdContactsByEmailResponses];

export type PatchAudiencesByAudienceIdContactsByEmailData = {
  body?: never;
  path: {
    /**
     * The Contact email.
     */
    email: string;
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts/{email}";
};

export type PatchAudiencesByAudienceIdContactsByEmailResponses = {
  /**
   * OK
   */
  200: UpdateContactResponseSuccess;
};

export type PatchAudiencesByAudienceIdContactsByEmailResponse =
  PatchAudiencesByAudienceIdContactsByEmailResponses[keyof PatchAudiencesByAudienceIdContactsByEmailResponses];

export type DeleteAudiencesByAudienceIdContactsByIdData = {
  body?: never;
  path: {
    /**
     * The Contact ID.
     */
    id: string;
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts/{id}";
};

export type DeleteAudiencesByAudienceIdContactsByIdResponses = {
  /**
   * OK
   */
  200: RemoveContactResponseSuccess;
};

export type DeleteAudiencesByAudienceIdContactsByIdResponse =
  DeleteAudiencesByAudienceIdContactsByIdResponses[keyof DeleteAudiencesByAudienceIdContactsByIdResponses];

export type GetAudiencesByAudienceIdContactsByIdData = {
  body?: never;
  path: {
    /**
     * The Contact ID.
     */
    id: string;
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts/{id}";
};

export type GetAudiencesByAudienceIdContactsByIdResponses = {
  /**
   * OK
   */
  200: GetContactResponseSuccess;
};

export type GetAudiencesByAudienceIdContactsByIdResponse =
  GetAudiencesByAudienceIdContactsByIdResponses[keyof GetAudiencesByAudienceIdContactsByIdResponses];

export type PatchAudiencesByAudienceIdContactsByIdData = {
  body?: UpdateContactOptions;
  path: {
    /**
     * The Contact ID.
     */
    id: string;
    /**
     * The Audience ID.
     */
    audience_id: string;
  };
  query?: never;
  url: "/audiences/{audience_id}/contacts/{id}";
};

export type PatchAudiencesByAudienceIdContactsByIdResponses = {
  /**
   * OK
   */
  200: UpdateContactResponseSuccess;
};

export type PatchAudiencesByAudienceIdContactsByIdResponse =
  PatchAudiencesByAudienceIdContactsByIdResponses[keyof PatchAudiencesByAudienceIdContactsByIdResponses];

export type GetBroadcastsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/broadcasts";
};

export type GetBroadcastsResponses = {
  /**
   * OK
   */
  200: ListBroadcastsResponseSuccess;
};

export type GetBroadcastsResponse =
  GetBroadcastsResponses[keyof GetBroadcastsResponses];

export type PostBroadcastsData = {
  body?: CreateBroadcastOptions;
  path?: never;
  query?: never;
  url: "/broadcasts";
};

export type PostBroadcastsResponses = {
  /**
   * OK
   */
  201: CreateBroadcastResponseSuccess;
};

export type PostBroadcastsResponse =
  PostBroadcastsResponses[keyof PostBroadcastsResponses];

export type DeleteBroadcastsByIdData = {
  body?: never;
  path: {
    /**
     * The Broadcast ID.
     */
    id: string;
  };
  query?: never;
  url: "/broadcasts/{id}";
};

export type DeleteBroadcastsByIdResponses = {
  /**
   * OK
   */
  200: RemoveBroadcastResponseSuccess;
};

export type DeleteBroadcastsByIdResponse =
  DeleteBroadcastsByIdResponses[keyof DeleteBroadcastsByIdResponses];

export type GetBroadcastsByIdData = {
  body?: never;
  path: {
    /**
     * The Broadcast ID.
     */
    id: string;
  };
  query?: never;
  url: "/broadcasts/{id}";
};

export type GetBroadcastsByIdResponses = {
  /**
   * OK
   */
  200: GetBroadcastResponseSuccess;
};

export type GetBroadcastsByIdResponse =
  GetBroadcastsByIdResponses[keyof GetBroadcastsByIdResponses];

export type PostBroadcastsByIdSendData = {
  body?: SendBroadcastOptions;
  path: {
    /**
     * The Broadcast ID.
     */
    id: string;
  };
  query?: never;
  url: "/broadcasts/{id}/send";
};

export type PostBroadcastsByIdSendResponses = {
  /**
   * OK
   */
  200: SendBroadcastResponseSuccess;
};

export type PostBroadcastsByIdSendResponse =
  PostBroadcastsByIdSendResponses[keyof PostBroadcastsByIdSendResponses];
